---
# tasks file for cca.splunk.enterprise-install
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.3.2


- name: Start splunk on command line
  ansible.builtin.command:
    cmd: "timeout {{ cca_splunk_command_timeout | default('120') }} {{ start_command }}"
  when:
    - stat_splunk_enterprise_bin.stat.exists
    - stat_ansible_managed.stat.exists
    - ensure_splunkd_started | default(true)
  changed_when: false
