---
# tasks file for cca.splunk.enterprise-install
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.1.1

- name: Find Splunk install file in repo directory
  become: false
  delegate_to: localhost
  connection: local
  ansible.builtin.find:
    paths: "{{ absolute_infrastructure_repo_path }}/splunk/var/images/"
    patterns: "splunk-{{ splunk_enterprise_version }}-*64.tgz"
  register: find_cca_splunk_tgz

- name: Find all Splunk tgz files in the tmp directory
  ansible.builtin.find:
    paths: "{{ cca_splunk_var_tmp }}"
    patterns: 'splunk-*-Linux-x86_64.tgz'
  register: find_cca_splunk_tmp_tgz

- name: Cleanup all Splunk tgz files in tmp except current version
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_cca_splunk_tmp_tgz.files }}"
  when: "'splunk-' ~ splunk_enterprise_version not in item.path"

- name: Assert that we have a matching splunk tgz file
  become: false
  delegate_to: localhost
  connection: local
  ansible.builtin.assert:
    that:
      find_cca_splunk_tgz.files | length == 1
    fail_msg: >-
      Found {{ find_cca_splunk_tgz.files | length }} Splunk install files on the
      host that matches splunk-{{ splunk_enterprise_version }}-*64.tgz.
      Download one using this command,
      ${CCA_REPO_DIR}/roles/cca.splunk.enterprise-install/files/bin/download_splunk_enterprise.sh
  when:
    - not stat_splunk_enterprise_bin.stat.exists or
      enterprise_upgrade | default(false)

- name: Stage splunk_cca files used during initial install or upgrade of Splunk Enterprise
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ cca_splunk_var_tmp }}/"
    recursive: true
    checksum: true
    archive: false
    rsync_path: '{% if splunk_user == ansible_ssh_user %}rsync{% else %}sudo -u {{ splunk_user }} rsync{% endif %}'
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_opts:
      - "--include=dat/untracked_files_splunk_{{ splunk_enterprise_version }}_Linux.diff"
      - "--include=bin/sudo_ansible_helper.sh"
      - "--include=bin/splunk_upgrade_cleanup.sh"
      - "--exclude=dat/*"
  check_mode: false

- name: Stage Splunk tgz file at initial install or upgrade of Splunk Enterprise
  ansible.posix.synchronize:
    src: "{{ absolute_infrastructure_repo_path }}/splunk/var/images/"
    dest: "{{ cca_splunk_var_tmp }}/"
    recursive: true
    checksum: true
    archive: false
    rsync_path: '{% if splunk_user == ansible_ssh_user %}rsync{% else %}sudo -u {{ splunk_user }} rsync{% endif %}'
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_opts:
      - "--include=splunk-{{ splunk_enterprise_version }}-*-*inux-*64.tgz"
      - "--exclude=*"
  check_mode: false
