---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.2.1

- name: "DRY RUN: Get yum update status"
  ansible.builtin.yum:
    name: "{{ cca_control.package.updates.include_packages }}"
    state: latest
    exclude: "{{ cca_control.package.updates.exclude_packages }}"
  register: yum_update_status
  check_mode: true
  tags:
    - skip_ansible_lint

- name: Debug yum stdout response
  ansible.builtin.debug:
    msg: "{{ yum_update_status }}"
    verbosity: 2

- name: Set fact if kernel update is detected
  ansible.builtin.set_fact:
    kernel_update_needed: true
  when: item | regex_search('kernel')
  with_items:
    - "{{ yum_update_status.changes.updated | default('') | list }}"
    - "{{ yum_update_status.changes.installed | default('') | list }}"
    - "{{ yum_update_status.results | default('') | list }}"

- name: Get pending actions
  ansible.builtin.include_role:
    name: cca.core.linux
    tasks_from: check_pending_actions.yml

- name: End play for this host due to this reason
  ansible.builtin.debug:
    msg: "{{ yum_update_status.results }}"
  when:
    - yum_update_status.results is defined
    - yum_update_status.results | list | regex_search('Nothing to do here, all packages are up to date')
    - not stat_server_reboot_pending.stat.exists | default(false)
    - not config_update | default(false)

- name: End play for host if nothing needs to be done
  ansible.builtin.meta: end_host
  when:
    - yum_update_status.results is defined
    - yum_update_status.results | list | regex_search('Nothing to do here, all packages are up to date')
    - not stat_server_reboot_pending.stat.exists | default(false)
    - not config_update | default(false)
