---
# tasks file for cca.splunk.onboarding
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.1.1

- name: DRY RUN - Perform a dry run of the staged files towards the target to collect rsync changes
  become: false
  ansible.posix.synchronize:
    src: '{{ manager_apps_staging_dir }}/'
    dest: '{{ splunk_path }}/etc/{{ cluster_manager_config_bundle_dir }}/'
    copy_links: true
    recursive: true
    checksum: true
    times: false
    delete: true
    owner: false
    group: false
    archive: false
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_path: '{% if splunk_user == ansible_ssh_user %}rsync{% else %}sudo -u {{ splunk_user }} rsync{% endif %}'
    rsync_opts: '{{ manager_apps_rsync_opts + item.rsync_opts if item.rsync_opts is defined else manager_apps_rsync_opts }}'
  register: cluster_apps_update_status
  check_mode: true
  no_log: "{{ hide_password }}"
  changed_when: false

- name: Assert that no unexpected directories wil be deleted on the cluster manager
  ansible.builtin.assert:
    that: not item | regex_search('\*deleting\s+[A-Za-z_\-0-9]+\/[A-Za-z_\-0-9]+\/$')
    success_msg: 'No critical app directories will be deleted on the cluster manager'
    fail_msg: >-
      An app directory deletion is detected on the cluster_manager. This is not allowed by
      default. If you expect these directories to be deleted, set accept_manager_app_removal
      to true in the extra_vars CCA dialogue.
  with_items: "{{ cluster_apps_update_status.stdout_lines | default('') | list }}"
  when:
    - not accept_manager_app_removal | default(false)

- name: Deploy the apps from the staging directory to the cluster manager
  become: false
  ansible.posix.synchronize:
    src: '{{ manager_apps_staging_dir }}//'
    dest: '{{ splunk_path }}/etc/{{ cluster_manager_config_bundle_dir }}/'
    copy_links: true
    recursive: true
    checksum: true
    times: false
    delete: true
    owner: false
    group: false
    archive: false
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_path: '{% if splunk_user == ansible_ssh_user %}rsync{% else %}sudo -u {{ splunk_user }} rsync{% endif %}'
    rsync_opts: '{{ manager_apps_rsync_opts + item.rsync_opts if item.rsync_opts is defined else manager_apps_rsync_opts }}'
  notify: notify cluster bundle push

- name: Cleanup manager after staging apps are completed
  become: false
  connection: local
  ansible.builtin.file:
    path: '{{ manager_apps_staging_dir }}'
    state: absent
  delegate_to: localhost
  when:
    - cluster_label is defined
    - cleanup_staging_apps | default(true)
  changed_when: false
  check_mode: false
