---
# tasks file for cca.splunk.onboarding
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.2.1

- name: DRY RUN - Perform a dry run of the staged files towards the target to collect rsync changes
  become: false
  ansible.posix.synchronize:
    src: '{{ deployment_server_apps_staging_dir }}/deployment_server/'
    dest: '{{ splunk_path }}/etc/deployment-apps/'
    copy_links: true
    recursive: true
    checksum: true
    times: false
    delete: true
    owner: false
    group: false
    archive: false
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_path: '{% if splunk_user == ansible_ssh_user %}rsync{% else %}sudo -u {{ splunk_user }} rsync{% endif %}'
    rsync_opts: '{{ deployment_apps_rsync_opts + item.rsync_opts if item.rsync_opts is defined else deployment_apps_rsync_opts }}'
  register: deployment_apps_update_status
  no_log: "{{ hide_password }}"
  check_mode: true
  changed_when: false
