---
# tasks file for cca.splunk.onboarding
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.2.1

- name: Set staging directory
  ansible.builtin.set_fact:
    manager_apps_staging_dir: '{{ (cca_local_tmp_dir | default("/tmp")) }}/{{ cca_runid }}/{{ environment_name }}/{{ inventory_hostname }}/{{ cluster_label }}'

- name: Cleanup manager before staging apps
  become: false
  connection: local
  ansible.builtin.file:
    path: '{{ manager_apps_staging_dir }}'
    state: absent
  delegate_to: localhost
  when:
    - cluster_label is defined
  changed_when: false
  check_mode: false

- name: Ensure directory exists for staging apps
  become: false
  delegate_to: localhost
  connection: local
  ansible.builtin.file:
    path: '{{ manager_apps_staging_dir }}'
    state: directory
    mode: '0700'
  changed_when: false
  check_mode: false

- name: Stage manager with manager apps from cluster directory
  become: false
  connection: local
  ansible.builtin.command: >
    rsync --delay-updates -F --compress --archive
    "{{ manager_apps_absolute_sourcedir | default(absolute_file_store_path + '/etc/' + manager_apps_sourcedir) }}/"
    "{{ manager_apps_staging_dir }}/"
  delegate_to: localhost
  when:
    - cluster_label is defined
  changed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

- name: Stage manager with selected manager apps
  become: false
  connection: local
  ansible.builtin.command: >
    rsync --delay-updates -F --compress --archive
    "{{ selected_manager_apps_absolute_sourcedir | default(absolute_file_store_path + '/etc/' + selected_manager_apps_sourcedir) }}/{{ item.source_app }}/"
    "{{ manager_apps_staging_dir }}/{{ item.name }}/"
  delegate_to: localhost
  when:
    - selected_manager_apps_sourcedir is defined
    - item.state is defined
    - item.state != 'absent'
  loop: '{{ selected_manager_apps | default([]) if selected_manager_apps | default([]) is iterable else [] }}'
  changed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

- name: "Stage manager with versioned apps destined for cluster manager in folder  {{ cluster_manager_config_bundle_dir }}"
  become: false
  connection: local
  ansible.builtin.command: >
    rsync --delay-updates -F --compress --archive
    "{{ (item.source_path | default(versioned_apps_source_path)) ~ ('/' ~ item.source_app if item.source_app is defined else '') }}/"
    "{{ manager_apps_staging_dir }}/{{ item.name }}/"
  delegate_to: localhost
  when:
    - versioned_apps_sourcedir is defined
    - item.dest_dir is defined
    - item.dest_dir == 'manager-apps' or
      item.dest_dir == 'master-apps'
    - item.state is defined
    - item.state != 'absent'
  loop: '{{ versioned_apps | default([]) if versioned_apps | default([]) is iterable else [] }}'
  changed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

- name: "Stage manager with selected apps destined for cluster manager in folder  {{ cluster_manager_config_bundle_dir }}"
  become: false
  connection: local
  ansible.builtin.command: >
    rsync --delay-updates -F --compress --archive
    "{{ (item.source_path | default(selected_apps_source_path)) ~ ('/' ~ item.source_app if item.source_app is defined else '') }}/"
    "{{ manager_apps_staging_dir }}/{{ item.name }}/"
  delegate_to: localhost
  when:
    - selected_apps_source_path is defined
    - item.dest_dir is defined
    - item.dest_dir == 'manager-apps' or
      item.dest_dir == 'master-apps'
    - item.state is defined
    - item.state != 'absent'
  loop: '{{ selected_apps | default([]) if selected_apps | default([]) is iterable else [] }}'
  changed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

- name: Include and run tasks from custom onboarding roles
  ansible.builtin.include_role:
    name: '{{ external_onboarding_role }}'
  loop_control:
    loop_var: external_onboarding_role
  loop: '{{ external_onboarding_masterapps_roles | default([]) if external_onboarding_masterapps_roles | default([]) is iterable else [] }}'
