---
# tasks file for cca.core.splunk
#
# Description: Login to splunk on cluster manager that relates to the host
#              given as cluster_manager_loop_var variable from outer loop.
#              Disable splunk maintenance-mode on the cluster manager.
#
# Prerequisite: This tasks must be include in an outer task that sets the
#               cluster_manager inventory name and passes that in the include_tasks
#               module.
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.2.1

- name: Ensure that splunk is running
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('120') }} {{ start_command }}
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: "{{ cca_splunkd_start_retries | default(10) | int }}"
  delay: 10
  changed_when:
    - false
  delegate_to: "{{ cluster_manager_loop_var }}"

- name: Verify that Splunk is running
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk status
      --accept-license
      --answer-yes
      --no-prompt
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: "{{ cca_splunkd_status_retries | default(10) | int }}"
  delay: 10
  changed_when: false
  check_mode: false
  delegate_to: "{{ cluster_manager_loop_var }}"
  tags:
    - skip_ansible_lint

- name: Splunk login
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk login
      --accept-license
      --answer-yes
      --no-prompt -auth '{{ splunk_cli_user }}:{{ splunk_cli_user_password }}'
  register: splunk_login_result
  no_log: "{{ hide_password }}"
  until: splunk_login_result.rc == 0
  retries: "{{ cca_splunk_login_retries | default(10) | int }}"
  delay: 10
  failed_when: false
  changed_when: false
  check_mode: false
  delegate_to: "{{ cluster_manager_loop_var }}"
  tags:
    - skip_ansible_lint

- name: Assert to find out if the login was successful
  ansible.builtin.assert:
    that:
      - splunk_login_result.rc | int == 0
    fail_msg: >-
      Splunk command or login failed with the reason (
      {{ splunk_login_result.stderr | default('Skipped task, disregard this stderr message') }} )
      Splunk command had an unexpected result if this is not blank (
      {{ splunk_login_result.stdout | default('Skipped task, disregard this stderr message') }}
      Return code ={{ splunk_login_result.rc }} )
    success_msg: >-
      Login successful
  delegate_to: "{{ cluster_manager_loop_var }}"

- name: Disable maitenance mode
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('30') }} {{ splunk_path }}/bin/splunk disable maintenance-mode
      --answer-yes --no-prompt
  delegate_to: "{{ cluster_manager_loop_var }}"
  tags:
    - skip_ansible_lint

- name: Splunk logout
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk logout
  register: splunk_logout_result
  until: splunk_logout_result.rc == 0
  retries: "{{ cca_splunk_logout_retries | default(60) | int }}"
  delay: 10
  failed_when: false
  changed_when: false
  check_mode: false
  delegate_to: "{{ cluster_manager_loop_var }}"
  tags:
    - skip_ansible_lint
