---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.2.2.1


- name: Put SELinux in desired mode
  selinux:
    policy: targeted
    state: "{{ cca_selinux_state | default('disabled') }}"
  notify: notify server reboot
