---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.2.1
# Configure systemd limits for Splunk user

- name: 'Set ulimits - hard nofile for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: nofile
    limit_type: hard
    value: '256000'
    use_max: true
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'
  notify: notify server reboot

- name: 'Set ulimits - soft nofile for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: nofile
    limit_type: soft
    value: '128000'
    use_max: true
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'

- name: 'Set ulimits - hard noproc for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: nproc
    limit_type: hard
    value: '64000'
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'
  notify: notify server reboot

- name: 'Set ulimits - soft nproc for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: nproc
    limit_type: soft
    value: '32000'
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'

- name: 'Set ulimits - hard fsize for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: fsize
    limit_type: hard
    value: '-1'
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'

- name: 'Set ulimits - soft fsize for {{ splunk_user }}'
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_item: fsize
    limit_type: soft
    value: '-1'
    dest: '/etc/security/limits.d/10-{{ splunk_user }}.conf'
