---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.3.1

- name: Reboot the server and wait for it to come back
  ansible.builtin.reboot:
    reboot_timeout: 1200
    post_reboot_delay: 30
  register: server_reboot_status

- name: Delete statefile based on reboot status
  ansible.builtin.file:
    path: "{{ server_reboot_pending | default('/tmp/server_reboot.pending') }}"
    state: 'absent'
  when:
    - server_reboot_status.rebooted
  check_mode: false
