---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.2.2

- name: Include task to check Splunk status
  ansible.builtin.include_tasks:
    ../cca.splunk.enterprise-install/tasks/splunk_status.yml

- name: Include tasks to login to splunk cli
  ansible.builtin.include_tasks:
    splunk_login.yml

- name: Splunk offline command, be patient, might take up to 10 min
  ansible.builtin.command:
    cmd: "timeout 900 {{ splunk_path }}/bin/splunk offline"
  changed_when: false
  when:
    - enterprise_upgrade | default(false) or
      kernel_update_needed | default(false) or
      stat_server_reboot_pending.exists | default(false) or
      stat_splunk_service_restart_pending.exists | default(false)
