---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Robin Blomdahl
#
# Release: 2025.2.1

- name: Ensure Chrony is installed and updated
  ansible.builtin.yum:
    name: chrony
    state: present
  tags:
    - skip_ansible_lint
