---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Robin Blomdahl
#
# Release: 2023.3.2

- name: Ensure polkit is installed and updated, CVE-2021-3560 is solved in version 0.115.12
  ansible.builtin.apt:
    name: policykit-1
    state: present
