---
# tasks file for cca.splunk.ssl-certificates
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.3.2
# facts_variable: 'cca_splunk_web_ssl' is set in validate_target_certificates.yml
# for manual certs with no fallback for selfsigned certificates.
- name: Set fact for web cert to be used in common tasks
  ansible.builtin.set_fact:
    cert_file_name: '{{ cca_splunk_certs_web_cert }}'
    cert_staging_file_name: '{{ cca_splunk_certs_web_staging_cert }}'
    privkey_file_name: '{{ cca_splunk_certs_web_key }}'
    privkey_staging_file_name: '{{ cca_splunk_certs_web_staging_key }}'
    privkey_password: '{{ cca_splunk_certs_web_sslpassword }}'
    facts_variable: 'cca_splunk_web_ssl'
    cert_type: 'web'
  no_log: "{{ hide_password }}"

- name: Include task that includes common certificate tasks
  ansible.builtin.include_tasks: certificates_main.yml
