---
# tasks file for cca.core.splunk
#
# Description: Add a search peer to a splunk server.
#
# Prerequisite: This task needs a outher task that loops over server and pass host as the
#               loop variable.
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.2.1

- name: "Add {{ host }} as a search peers to {{ inventory_hostname }}"
  delegate_to: "{{ inventory_hostname }}"
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('60') }}
      {{ splunk_path }}/bin/splunk add search-server {{ host }}:{{ splunk_enterprise_mgmt_port }}
      -remoteUsername {{ splunk_cli_user }}
      -remotePassword {{ splunk_cli_user_password }}
      -auth '{{ splunk_cli_user }}:{{ splunk_cli_user_password }}'
  register: command_result
  failed_when:
    - command_result.rc != 0
    - command_result.rc != 24
  changed_when:
    - command_result.rc == 0
  no_log: "{{ hide_password }}"
  tags:
    - skip_ansible_lint
