---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Robin Blomdahl
#
# Release: 2024.1.2

- name: Ensure Chrony is installed and updated
  ansible.builtin.apt:
    name: chrony
    state: latest