---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist
#
# Release: 2024.1.2

- name: Set fact for current_item
  ansible.builtin.set_fact:
    current_item:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
  with_dict:
    - "{{ secret_type }}"

- name: Set fact for secret_password
  ansible.builtin.set_fact:
    secret_password: "{{ cca_environment.default_server_general_pass4symmkey }}"
  when: not current_item.key | regex_search('default')

- name: Set fact for secret_password
  ansible.builtin.set_fact:
    secret_password: 'password'
  when: current_item.key | regex_search('default')

- name: Encrypt the password
  ansible.builtin.command:
    cmd: "python3 {{ role_path }}/../cca.core.splunk/files/bin/splunk_secret_helper.py --splunk-secret {{ splunk_secret }} --cleartext '{{ secret_password }}'"
  register: encrypted_random_secret
  tags:
    - skip_ansible_lint

- name: Assert that the password encryption command was successful
  ansible.builtin.assert:
    that:
      - encrypted_random_secret.stderr == ''

- name: Vault the secret password
  ansible.builtin.set_fact:
    vaulted_secret_value: >-
      {{ secret_password | vault(lookup('ansible.builtin.file', ansible_env.ANSIBLE_VAULT_PASSWORD_FILE))
      | split() | join('\r\n')
      | regex_replace('1.2;AES256;filter_default', '1.1;AES256') }}

- name: Save the clear text secret as an ansible vault
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: '{{ current_item.key }}_{{ current_item.value }}: !vault "{{ vaulted_secret_value }}"'
    regex: '^{{ current_item.key }}_{{ current_item.value }}:'

- name: Save the secret hash to the file
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: "{{ current_item.key }}_{{ current_item.value }}_hash: '{{ encrypted_random_secret.stdout }}'"
    regex: '^{{ current_item.key }}_{{ current_item.value }}_hash:'
