---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Roger Lindquist (github.com/rlinq)
# META_DATE
# META_VERSION

- name: Include tasks to handle cgroup versions
  ansible.builtin.include_tasks: systemd/manage_cgroup_version.yml
