---
# tasks file for cca.core.splunk
#
# Description: This tasks parse the output of the task that configure splunk
#              settings. Based on what items that has been updated different
#              notify actions is triggered.
#              Special actions is implemented for Splunk core, deployment-apps
#              shcluster and cm bundle directory (master-apps or manager-apps)
#              depending on Splunk version.
#
# Prerequisite:
#              splunk_settings_update must be defined and have results. This
#              task shall not be called stand alone.
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.1.2

- name: Determine actions based on configuration changes
  ansible.builtin.set_fact:
    splunk_actions: "{{ cca_splunk_settings_update.results |
                        analyze_splunk_changes(rolling_restart_pending=stat_rolling_restart_pending | default(false),
                        splunkd_restart_pending=stat_splunkd_restart_pending | default(false),
                        force_splunkd_restart=force_splunkd_restart | default(false),
                        force_bundle_push=force_bundle_push | default(false)) }}"

- name: Notify a standard splunkd restart if relevant changes are detected
  ansible.builtin.set_fact:
    splunkd_restart: true
  when:
    - splunk_actions.splunkd_restart_pending
  changed_when:
    - splunk_actions.splunkd_restart_pending
  notify: notify splunkd restart

- name: Notify a Deployment Server reload if deployment-apps content is updated
  ansible.builtin.set_fact:
    deploymentserver_reload: true
  when:
    - splunk_actions.deploymentserver_reload
  changed_when:
    - splunk_actions.deploymentserver_reload
  notify: notify deploymentserver reload

- name: Notify a Search Head Deployer push if shcluster content is updated
  ansible.builtin.set_fact:
    deployer_push: true
  when:
    - splunk_actions.deployer_push
  changed_when:
    - splunk_actions.deployer_push
  notify: notify shcluster bundle push

- name: Notify a Search Head Deployer push if a forced push option is true
  ansible.builtin.set_fact:
    deployer_push: true
  when:
    - force_bundle_push | default(false)
  changed_when:
    - force_bundle_push | default(false)
  notify: notify shcluster bundle push
  no_log: '{{ hide_password }}'

- name: Notify a Cluster Manager push if bundle directory content is updated
  ansible.builtin.set_fact:
    cluster_manager_push: true
  when:
    - splunk_actions.cluster_manager_push
  changed_when:
    - splunk_actions.cluster_manager_push
  notify: notify cluster bundle push
