---
# tasks file for cca.core.splunk
#
# Description: This tasks reads the splunk_conf_group_settings_flattened and
#              apply them on each splunk host that is targeted by the
#              playbook.
#
# Prerequisite:
#   splunk_conf_group_settings_flattened needs to be defined
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.1.2

- name: Manage header line in splunk files, managed by ansible
  community.general.ini_file:
    path: "{{ item.path }}"
    section:
    option: '{{ file_managed_by_ansible }}'
    value: null
    state: present
    allow_no_value: true
    mode: '0644'
  loop:
    "{{ splunk_conf_group_settings_flattened }}"
  changed_when: false
  no_log: '{{ hide_password }}'

- name: Updates Splunk conf based on group settings
  community.general.ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option | default(null) if item.state | default('present') != 'AbsentSection' else '' }}"
    value: "{{ item.value | default(null) if item.state | default('present') != 'AbsentSection' else '' }}"
    state: "{{ 'present' if item.state | default('present') == 'present' else 'absent' }}"
    allow_no_value: "{{ 'yes' if (not item.value) else 'no' }}"
    mode: '0644'
  loop: "{{ splunk_conf_group_settings_flattened }}"
  loop_control:
    label: "{{ item.section }} - {{ item.option }}"
  register: cca_splunk_settings_update

- name: Include task to notify restart or need to push group settings
  ansible.builtin.include_tasks: notify_splunk.yml
  when:
    - cca_splunk_settings_update is defined
    - cca_splunk_settings_update.results is defined
