---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.2.1

- name: Verify that Splunk is running
  ansible.builtin.command:
    cmd: "timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk status --accept-license --answer-yes --no-prompt"
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: "{{ cca_splunkd_status_retries | default(10) | int }}"
  delay: 10
  changed_when: false
  check_mode: false

- name: Splunk logout
  ansible.builtin.command:
    cmd: "timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk logout"
  register: splunk_logout_result
  until: splunk_logout_result.rc == 0
  retries: "{{ cca_splunk_logout_retries | default(60) | int }}"
  delay: 10
  failed_when: false
  changed_when: false
  check_mode: false

- name: Debug any error and fail task if logout wasn't successful
  ansible.builtin.debug:
    msg: >-
      Splunk command or logout failed with the reason (
      {{ splunk_logout_result.stderr | default('Skipped task, disregard this stderr message') }} )
      Splunk command had an unexpected result if this is not blank (
      {{ splunk_logout_result.stdout | default('Skipped task, disregard this stderr message') }} )
  when:
    - splunk_logout_result.rc > 0
  failed_when:
    - splunk_logout_result.rc > 0
