---
# Playbook to generate Splunk encrypted string and ansible vault string
#
# REPO_TYPE=infrastructure
# MENU_DESC=Generate Splunk secret and ansible vault string
# EXTRA_VARS=hide_password(true)

- name: Playbook to generate Splunk encrypted string and ansible vault string
  hosts: localhost
  connection: local
  gather_facts: true
  vars_prompt:
    - name: "secret_password"
      prompt: "Enter the password to hash and encrypt (no echo)"
      private: true

  tasks:
    - name: Encrypt the password
      ansible.builtin.command:
        cmd: >
          python3 {{ lookup('env', 'CCA_REPO_DIR') }}/roles/cca.core.splunk/files/bin/splunk_secret_helper.py
          --splunk-secret {{ cca_splunk_secret }}
          --cleartext '{{ secret_password }}'
      register: encrypted_random_secret
      changed_when: false
      when: secret_password is defined
      no_log: "{{ hide_password | default(true) }}"

    - name: Vault the secret password
      ansible.builtin.set_fact:
        vaulted_secret_value: >-
          {{ secret_password | vault(lookup('ansible.builtin.file', ansible_env.ANSIBLE_VAULT_PASSWORD_FILE))
          | split() | join('\r\n')
          | regex_replace('1.2;AES256;filter_default', '1.1;AES256') }}
      when: secret_password is defined
      no_log: "{{ hide_password | default(true) }}"

    - name: Print the encrypted and vaulted secret
      ansible.builtin.debug:
        msg: |
          my_secret_hash: {{ encrypted_random_secret.stdout }}
          my_secret: !vault "{{ vaulted_secret_value }}"
      when:
        - encrypted_random_secret.stdout is defined
        - vaulted_secret_value is defined
