---
# MENU_DESC=Deploy onboarding apps towards all instances
# REPO_TYPE=onboarding
# EXTRA_VARS=hide_password(true) accept_manager_app_removal(true) accept_shc_app_removal(true) accept_deployment_app_removal(true) force_bundle_push(false)
#

- name: Deploy apps to Cluster Managers
  import_playbook: deploy_manager_apps.yml
  vars:
    accept_manager_app_removal: true

- name: Deploy apps to Search Head Clusters
  import_playbook: deploy_shcluster_apps.yml
  vars:
    accept_shc_app_removal: true

- name: Deploy apps to Deployment Servers
  import_playbook: deploy_deployment_apps.yml
  vars:
    accept_deployment_app_removal: true

- name: Deploy apps to Splunk Servers
  import_playbook: deploy_apps.yml
