# Playbook to handle Hybrid Search Heads
#
# REPO_TYPE=infrastructure
# MENU_DESC=Manage Hybrid Searchheads
# EXTRA_VARS=hide_password(true)

- name: Initialize playbook run on manager server - Hybrid Search Heads
  hosts: manager
  connection: local
  strategy: linear
  any_errors_fatal: true
  pre_tasks:
    - name: Include initialize task
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          initialize.yml
      vars:
        target: "hybrid_searchheads"


- name: Verify that connection to all servers are ok before we start
  hosts: hybrid_searchheads
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  gather_facts: false
  strategy: linear
  any_errors_fatal: true
  pre_tasks:
    - name: Include tasks to wait for connection to host
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          wait_for_connection.yml

    - name: Include pre tasks
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          pre_tasks.yml


- name: Configure the hybrid search head
  hosts: hybrid_searchheads
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  gather_facts: false
  serial: 1
  any_errors_fatal: true
  pre_tasks:
    - name: Gather only network facts
      ansible.builtin.setup:
        gather_subset: 'network'

    - name: Debug all vars
      ansible.builtin.debug:
        msg: '{{ hostvars[inventory_hostname] }}'
      when:
        debug | default(false)

  tasks:
    - name: Ensure Splunk is installed
      ansible.builtin.include_role:
        name: cca.splunk.enterprise-install

    - name: Configure server certificate in Splunk
      ansible.builtin.include_role:
        name: cca.splunk.ssl-certificates
        tasks_from:
          server_certificate.yml

    - name: Configure web server certificate in Splunk
      ansible.builtin.include_role:
        name: cca.splunk.ssl-certificates
        tasks_from:
          web_certificate.yml

    - name: Include role to configure outputs certificates
      ansible.builtin.include_role:
        name: cca.splunk.ssl-certificates
        tasks_from:
          outputs_certificate.yml

    - name: Configure settings for Splunk UI
      ansible.builtin.include_role:
        name: cca.splunk.frontend

    - name: Manage Splunk conf settings
      ansible.builtin.include_role:
        name: cca.core.splunk

    - name: Manage settings for the Splunk user profile
      ansible.builtin.include_role:
        name: cca.splunk.user-profile
        tasks_from:
          configure_user_profile.yml

  post_tasks:
    - name: Check if there is any pending actions
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          check_pending_actions.yml

    - name: Restart splunkd if needed
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          restart_splunkd.yml
      when:
        - stat_splunkd_restart_pending.stat.exists

    - name: Include post tasks
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          post_tasks.yml


- name: Finalize playbook run on manager server
  hosts: manager
  connection: local
  strategy: linear
  pre_tasks:
    - name: Include finalize task
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          finalize.yml
      vars:
        target: "hybrid_searchheads"
