

 Server has been configured with CCA for Splunk.

   ____ ____    _       __              ____        _             _
  / ___/ ___|  / \     / _| ___  _ __  / ___| _ __ | |_   _ _ __ | | __
 | |  | |     / _ \   | |_ / _ \| '__| \___ \| '_ \| | | | | '_ \| |/ /
 | |__| |___ / ___ \  |  _| (_) | |     ___) | |_) | | |_| | | | |   <
  \____\____/_/   \_\ |_|  \___/|_|    |____/| .__/|_|\__,_|_| |_|_|\_\
                                             |_| by Innovationfleet

 While support is not included in this version, support is available in the
 commercial versions of CCA for Splunk. If interested, find more details at
 https://github.com/innovationfleet/cca_for_splunk
