---
# tasks file for cca.splunk.role-searchhead
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.3.2

- name: Include task to login
  ansible.builtin.include_tasks: splunk_login.yml

- name: Include task to check if Search head cluster is boot strapped
  ansible.builtin.include_role:
    name: cca.splunk.role-searchhead
    tasks_from: check_captain_init_status.yml

- name: Set fact if shcluster C1 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c1 | default([]) )

- name: Set fact if shcluster C2 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c2 | default([]) )

- name: Set fact if shcluster C3 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c3 | default([]) )

- name: Set fact if shcluster C4 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c4 | default([]) )

- name: Set fact if shcluster C5 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c5 | default([]) )

- name: Set fact if shcluster C6 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c6 | default([]) )

- name: Set fact if shcluster C7 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c7 | default([]) )

- name: Set fact if shcluster C8 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c8 | default([]) )

- name: Set fact if shcluster C9 is bootstrapped
  ansible.builtin.set_fact:
    status_shc_init: true
  when:
    - inventory_hostname in ( groups.searchhead_members_shcluster_c9 | default([]) )

- name: Wait until shcluster status is ok
  ansible.builtin.command:
    cmd: 'timeout 20 {{ splunk_path }}/bin/splunk show shcluster-status'
  register: shcluster_status_result
  until: "'service_ready_flag : 1' in shcluster_status_result.stdout | default('')"
  retries: "{{ shc_sync_retry_num | default('30') }}"
  delay: "{{ retry_delay | default('30') }}"
  failed_when: false
  changed_when: false
  check_mode: false
  when:
    - not status_shc_init
  tags:
    - skip_ansible_lint

- name: Wait until kvstore is ready
  ansible.builtin.command:
    cmd: >
      timeout {{ cca_splunk_command_timeout | default('60') }} {{ splunk_path }}/bin/splunk show kvstore-status
  register: kvstore_status
  retries: "{{ cca_splunk_kvstore_status_retries | default(6) | int }}"
  delay: 10
  until: "'status : ready' in kvstore_status.stdout | default('') | string"
  changed_when: false
  check_mode: false
  when:
    - not status_shc_init
  tags:
    - skip_ansible_lint

- name: Wait until rolling restart is completed
  ansible.builtin.command:
    cmd: 'timeout 20 {{ splunk_path }}/bin/splunk show shcluster-status'
  register: shcluster_status_result
  until: "'rolling_restart_flag : 0' in shcluster_status_result.stdout | default('')"
  retries: "{{ shc_sync_retry_num | default('30') }}"
  delay: "{{ retry_delay | default('30') }}"
  failed_when: false
  changed_when: false
  check_mode: false
  when:
    - not status_shc_init
